version: '3'
services:
  api:
    image: node:14
    command: yarn start
    working_dir: /app
    container_name: company_customers_api
    restart: unless-stopped
    ports:
      - ${SERVER_PORT:-8000}:8000
    networks:
      - api
      - db
    links:
      - db
    volumes:
      - ../api/:/app
    depends_on:
      - db

  db:
    build: 
      context: ../
      dockerfile: docker/mongo/Dockerfile
    container_name: company_customers_db
    restart: unless-stopped
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER:-customers}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWD:-bluecore}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME:-customers}
    volumes:
      - company_customers_db:/data/db

  web:
    image: node:14
    command: yarn start
    working_dir: /app
    container_name: company_customers_web
    restart: unless-stopped
    ports:
      - 80:3000
    networks:
      - api
    links:
      - api
    volumes:
      - ../web/:/app
    depends_on:
      - api

networks:
  api:
    driver: bridge
  db:
    driver: bridge

volumes:
  company_customers_db:
