version: '3'
services:
  api:
    image: node:14
    command: yarn start
    working_dir: /app
    container_name: company_customers_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - api
      - db
    links:
      - db
    volumes:
      - ../api/:/app
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: company_customers_db
    restart: unless-stopped
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - company_customers_db:/data/db

networks:
  api:
    driver: bridge
  db:
    driver: bridge

volumes:
  company_customers_db:
